config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'edit_profile', to: 'users#edit', as: :edit_profile
  patch 'update_profile', to: 'users#update', as: :update_profile

  resources :customers do
    get :search, on: :collection
  end

  resources :vehicles do
    resources :attachments, only: [:create]
    get 'publish', on: :member
    post 'prepare_to_publish', on: :member, as: :prepare_to_publish
  end

  resources :expenses
  resources :expense_categories do
    get :search, on: :collection
  end

  resources :attachments, only: [:destroy]
  resources :brands
  resources :vehicle_models do
    get :search, on: :collection
  end

  resources :versions, only: [:index, :create]
  resources :coincidences, except: [:edit, :new]
  resources :buyers
  resources :budgets
  resources :sales do
    get 'pre_print_advance_certificate', on: :member
    get 'pre_print_sale_certificate', on: :member
  end

  post 'print_pdf', to: 'printer#print_pdf'

  get 'login', to: 'user_sessions#new', as: :login
  post 'logout', to: 'user_sessions#destroy', as: :logout

  root 'vehicles#index'
end

app/models/vehicle.rb
# == Schema Information
#
# Table name: vehicles
#
#  id                         :integer          not null, primary key
#  brand_id                   :integer
#  vehicle_model_id           :integer
#  version_id                 :integer
#  customer_id                :integer
#  kilometers                 :integer
#  color                      :string
#  details                    :text
#  cost_in_cents              :integer
#  price_in_cents             :integer
#  entered_on                 :date
#  sold_on                    :date
#  is_consignment             :boolean          default(FALSE)
#  is_financed                :boolean          default(FALSE)
#  minimum_advance_in_cents   :integer
#  transfer_amount_in_cents   :integer
#  plate                      :string
#  year                       :integer
#  motor_number               :string
#  chassis_number             :string
#  created_at                 :datetime
#  updated_at                 :datetime
#  is_owner                   :boolean          default(FALSE)
#  has_automatic_transmission :boolean          default(FALSE)
#  is_hdi                     :boolean          default(FALSE)
#

class Vehicle < ActiveRecord::Base

  # -- Scopes
  default_scope -> { order(entered_on: :desc, created_at: :desc) }
  scope :not_sold, -> {
    joins('LEFT JOIN sales on sales.vehicle_id = vehicles.id')
      .where('sales.id is NULL OR sales.sold_on IS NULL').distinct
  }

  # -- Associations
  belongs_to :brand
  belongs_to :version
  belongs_to :vehicle_model
  belongs_to :customer
  has_many :attachments, dependent: :destroy
  has_many :budgets, dependent: :destroy
  has_many :coincidences, dependent: :destroy
  has_one :sale, dependent: :destroy

  # -- Validations
  validates :brand, presence: true
  validates :vehicle_model, presence: true
  validates :version, presence: true
  validates :customer, presence: true, if: :not_owner?
  # validates :entered_on, presence: true, if: :is_owner?
  validates :year, presence: true
  validates :kilometers, presence: true
  validates :color, presence: true
  validates :plate, uniqueness: true, allow_blank: true

  # -- Misc
  def not_owner?
    !is_owner?
  end
  
  def sold?
    sold_on.present?
  end

  # Para usar field_in_cents, etc.
  def self.attributes_in_cents
    ['cost', 'price', 'minimum_advance', 'transfer_amount']
  end

  include IntegerInCents

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  before_filter :set_vehicle, only: [:edit, :update, :destroy, :prepare_to_publish, :publish]

  def index
    @presenter = VehiclesPresenter.new(params)
  end

  def show
    @vehicle = Vehicle.find(params[:id]).decorate

    rescue ActiveRecord::RecordNotFound
      flash[:error] = 'El vehículo buscado no existe'
      redirect_to vehicles_path
  end

  def new
    @vehicle = Vehicle.new(vehicle_params)
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      CoincidenceFinder.call(vehicle: @vehicle)

      redirect_to @vehicle,
        notice: 'El vehículo ha sido creado correctamente.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        CoincidenceFinder.call(vehicle: @vehicle)
        format.json { respond_with_bip(@vehicle) }
        format.html {
          redirect_to vehicles_path,
            notice: 'El vehículo ha sido actualizado correctamente.'
        }
      else
        format.json { respond_with_bip(@vehicle) }
        format.html { render :edit }
      end
    end
  end

  def destroy
    if @vehicle.destroy
      redirect_to vehicles_path,
        notice: 'El vehículo ha sido eliminado correctamente.'
    else
      flash[:error] = 'Ocurrió un error al eliminar el vehículo'
      redirect_to vehicles_path
    end
  end

  # Try to gets token from Facebook to publish and redirects to /publish
  def prepare_to_publish
    manager = OauthManager.new(@vehicle)
    @oauth = manager.oauth
    redirect_to manager.url

    rescue Exception => e
      flash[:error] = "No se pudo autenticar con Facebook. #{e}"
      redirect_to vehicles_path
  end

  def publish
    manager = OauthManager.new(@vehicle)
    page_token = manager.get_page_access_token(facebook_params[:code])
    response = FacebookPublisher.new(@vehicle.decorate, page_token).post()

    if response[:status] == :ok
      flash[:success] = 'El vehículo se ha publicado en Facebook exitosamente'
    else
      flash[:error] = 'Ocurrió un error al intentar conectarse con Facebook'
    end

    redirect_to @vehicle
  end


  private

  def facebook_params
    params.permit(:code)
  end

  def vehicle_params
    params.require(:vehicle).permit(:kilometers, :color, :details, :cost,
            :price, :entered_on, :sold_on, :is_exchange, :is_consignment,
            :is_financed, :minimum_advance, :transfer_amount, :plate,
            :year, :motor_number, :chassis_number, :vehicle_model_id,
            :is_hdi, :has_automatic_transmission, :vehicle_type,
            :version_id, :brand_id, :customer_id, :is_owner) if params[:vehicle].present?
  end

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

end

app/views/vehicles/show/_extra_data.html.erb
<div class="box box-primary">

  <div class="box-header with-border">
    <h3 class="box-title">
      <span class="fa fa-money"></span>
       Datos Extra
    </h3>
    <div class="box-tools pull-right">
      <button type="button" class="btn btn-box-tool" data-widget="collapse">
        <i class="fa fa-minus"></i>
      </button>
    </div>
  </div>

  <div class="box-body">

    <ul class="list-group list-group-unbordered">
      <li class="list-group-item" style="margin-top: 10px;">
        <b>HDI</b>
        <span class="text-muted pull-right"><%= vehicle.is_hdi %></span>
      </li>
      <li class="list-group-item">
        <b>Caja Automática</b>
        <span class="text-muted pull-right"><%= vehicle.has_automatic_transmission %></span>
      </li>
    </ul>

  </div>

</div>

app/views/vehicles/show/_financial_data.html.erb
<div class="box box-primary">
  
  <div class="box-header with-border">
    <h3 class="box-title">
      <span class="fa fa-money"></span>
       Financiación
    </h3>
    <div class="box-tools pull-right">
      <button type="button" class="btn btn-box-tool" data-widget="collapse">
        <i class="fa fa-minus"></i>
      </button>
    </div>
  </div>

  <div class="box-body">
    
    <ul class="list-group list-group-unbordered">
      <li class="list-group-item" style="margin-top: 10px;">
        <b>Permite financiación</b>
        <span class="text-muted pull-right"><%= vehicle.is_financed %></span>
      </li>
      <li class="list-group-item">
        <b>Adelanto mínimo</b>
        <span class="text-muted pull-right"><%= vehicle.minimum_advance %></span>
      </li>
    </ul>
    
  </div>

</div>

app/views/vehicles/show/_profile.html.erb
<div class="box box-primary">

  <div class="box-body box-profile">
    <h3 class="text-center"><%= vehicle.brand_and_model %></h3>
    <h4 class="text-center"><%= vehicle.version %></h4>
    <h4 class="text-center text-muted"><%= vehicle.plate %></h4> 
    <br />
    <h4 class="text-center"><b><%= vehicle.specs %></b></h4>
    <center>
      <%= link_to 'Editar', edit_vehicle_path(vehicle), class: 'btn btn-xs btn-primary' %>
      <%= link_to 'Eliminar', vehicle_path(vehicle), class: 'btn btn-xs btn-danger',
            method: :delete, data: { confirm: '¿Seguro?' } %>
    </center>

    <br />

    <ul class="list-group list-group-unbordered">
      <li class="list-group-item">
        <h2 class="text-center"><b><%= vehicle.price %></b></h2>
      </li>
      <li class="list-group-item">
        <b>Consignación</b>
        <span class="text-muted pull-right"><%= vehicle.is_consignment %></span>
      </li>
    </ul>

    <% if @vehicle.sale %>
      <div class="row">
        <div class="col-md-12">
          <p class="text-center text-muted"> <%= @vehicle.sale_situation_text %> </p>
        </div>
      </div>
    <% else %>

      <div class="row">
        <div class="col-md-12">
          <%= link_to '<b>Presupuestar</b>'.html_safe, new_budget_path(vehicle_id: vehicle.id),
            class: 'btn btn-warning btn-block margin-bottom-5' %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= link_to '<b>Publicar</b>'.html_safe, prepare_to_publish_vehicle_path(vehicle), method: :post,
            class: 'btn btn-primary btn-block margin-bottom-5' %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= link_to '<b>Iniciar Venta</b>'.html_safe, new_sale_path(vehicle_id: vehicle.id),
            class: 'btn btn-success btn-block' %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/vehicles/show/_register_data.html.erb
<div class="box box-primary">

  <div class="box-header with-border">
    <h3 class="box-title">
      <span class="fa fa-file-text-o"></span>
      Datos del registro
    </h3>
    <div class="box-tools pull-right">
      <button type="button" class="btn btn-box-tool" data-widget="collapse">
        <i class="fa fa-minus"></i>
      </button>
    </div>
  </div>

  <div class="box-body">

    <ul class="list-group list-group-unbordered">
      <li class="list-group-item" style="margin-top: 10px;">
        <b>Patente</b>
        <span class="text-muted pull-right"><%= vehicle.plate %></span>
      </li>
      <li class="list-group-item">
        <b>Número de motor</b>
        <span class="text-muted pull-right"><%= vehicle.motor_number %></span>
      </li>
      <li class="list-group-item">
        <b>Número de chasis</b>
        <span class="text-muted pull-right"><%= vehicle.chassis_number %></span>
      </li>
    </ul>

  </div>

</div>