config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'edit_profile', to: 'users#edit', as: :edit_profile
  patch 'update_profile', to: 'users#update', as: :update_profile

  resources :customers do
    get :search, on: :collection
  end

  resources :vehicles do
    resources :attachments, only: [:create]
    get 'publish', on: :member
    post 'prepare_to_publish', on: :member, as: :prepare_to_publish
  end

  resources :expenses
  resources :expense_categories do
    get :search, on: :collection
  end

  resources :attachments, only: [:destroy]
  resources :brands
  resources :vehicle_models do
    get :search, on: :collection
  end

  resources :versions, only: [:index, :create]
  resources :coincidences, except: [:edit, :new]
  resources :buyers
  resources :budgets
  resources :sales do
    get 'pre_print_advance_certificate', on: :member
    get 'pre_print_sale_certificate', on: :member
  end

  post 'print_pdf', to: 'printer#print_pdf'

  get 'login', to: 'user_sessions#new', as: :login
  post 'logout', to: 'user_sessions#destroy', as: :logout

  root 'vehicles#index'
end

app/models/budget.rb
# == Schema Information
#
# Table name: budgets
#
#  id                  :integer          not null, primary key
#  vehicle_id          :integer
#  vehicle_description :string
#  year                :integer
#  price_in_cents      :integer
#  minimum_advance     :integer
#  financed            :string           default("0")
#  installments        :string           default("0")
#  installments_cost   :string           default("0")
#  expenses            :string           default("0")
#  notes               :string
#  budgeted_on         :date
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Budget < ActiveRecord::Base

  # -- Associations
  belongs_to :vehicle

  # -- Validations
  validates :vehicle_description, presence: true
  validates :price, presence: true
  validates :budgeted_on, presence: true

  # Para usar field_in_cents, etc.
  def self.attributes_in_cents
    ['price']
  end

  include IntegerInCents

end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController

  before_filter :set_budget, only: [:edit, :update, :destroy]

  # GET /budgets
  def index
    @presenter = BudgetsPresenter.new(params)
    @budget_to_print = params[:print]
  end

  def show
    @budget = Budget.find(params[:id])
    pdf = BudgetPdf.new(@budget, view_context)
    send_data pdf.render, filename: "presupuesto_#{@budget.budgeted_on}",
              type: 'application/pdf',
              disposition: 'inline'
  end

  # GET /budgets/new
  def new
    @budget = new_budget_from_vehicle
  end

  # POST /budgets
  def create
    @budget = Budget.new(budget_params)
    if @budget.save
      redirect_to budgets_path(print: @budget.id), notice: 'El presupuesto ha sido creado con éxito'
    else
      render :new
    end
  end

  # GET /budgets/:id/edit
  def edit
  end

  # PUT /budgets/:id
  def update
    if @budget.update(budget_params)
      redirect_to budgets_path(print: @budget.id),
        notice: 'El presupuesto ha sido actualizado correctamente.'
    else
      render :edit
    end
  end

  # DELETE /budgets/:id
  def destroy
    if @budget.destroy
      redirect_to budgets_path,
        notice: 'El presupuesto ha sido eliminado correctamente.'
    else
      flash[:error] = 'Ocurrió un error al eliminar el presupuesto'
      redirect_to budgets_path
    end
  end

  private

  def set_budget
    @budget = Budget.find(params[:id])
  end

  def budget_params
    params.require(:budget).permit(:vehicle_id, :vehicle_description, :price,
                                   :minimum_advance, :financed, :installments,
                                   :installments_cost, :expenses, :notes,
                                   :budgeted_on, :year)

  end

  def new_budget_from_vehicle
    if params[:vehicle_id]
      vehicle_decorator = Vehicle.find(params[:vehicle_id]).decorate
      Budget.new(
        vehicle_id:          vehicle_decorator.id,
        budgeted_on:         Time.zone.today,
        vehicle_description: vehicle_decorator.identification,
        year:                vehicle_decorator.year,
        price:               vehicle_decorator.unformatted_price,
        minimum_advance:     vehicle_decorator.unformatted_minimum_advance
      )
    else
      Budget.new(budgeted_on: Time.zone.today)
    end

  end
end

app/views/budgets/_budget.html.erb
<tr id="<%= dom_id(budget) %>">

  <td> <%= link_to budget.budgeted_on, budget_path(budget, format: :pdf), target: :blank %> </td>
  <td class="text-center"> <%= budget.vehicle_description %> </td>
  <td class="text-center"> <%= budget.year %> </td>
  <td>
    <%= link_to 'Editar', edit_budget_path(budget), class: 'btn btn-xs btn-primary' %>
    <%= link_to 'Eliminar', budget, method: :delete,
        data: {confirm: '¿Está seguro?'}, class: 'btn btn-xs btn-danger' %>
  </td>

</tr>

app/views/budgets/_filter.html.erb
<%= form_for @presenter.filter, url: :budgets, method: :get do |f| %>

  <div class="row">
    <div class="col-md-12">

      <fieldset class="form-group">
        <div class="col-md-3">
          <fieldset class="form-group">
            <%= f.label :from %>
            <div class='input-group date datepicker'>
              <span class="input-group-addon">
                <span class="fa fa-calendar"></span>
              </span>
              <%= f.text_field :from, class: 'form-control' %>
            </div>
          </fieldset>
        </div>

        <div class="col-md-3">
          <fieldset class="form-group">
            <%= f.label :to %>
            <div class='input-group date datepicker'>
              <span class="input-group-addon">
                <span class="fa fa-calendar"></span>
              </span>
              <%= f.text_field :to, class: 'form-control' %>
            </div>
          </fieldset>
        </div>

        <div class="col-md-3">
          <div class="fake-label"></div>
          <%= f.submit 'Filtrar', class: 'btn btn-primary',
                  'data-disable-with' => 'Filtrando...' %>
          <%= link_to 'Limpiar', [:budgets], class: 'btn btn-default',
                'data-disable-with' => 'Espere...' %>
        </div>

      </fieldset>

    </div>
  </div>

<% end %>

app/views/budgets/_form.html.erb
<%= form_for @budget do |f| %>

  <%= f.hidden_field :vehicle_id %>

<article class="box box-primary">

  <section class="box-body">

    <div class="row">
      <div class="col-md-3">
        <fieldset class="form-group">
          <%= f.label :budgeted_on %>
          <div class='input-group date datepicker'>
            <span class="input-group-addon">
              <span class="fa fa-calendar"></span>
            </span>
            <%= f.text_field :budgeted_on, class: 'form-control' %>
          </div>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <fieldset class="form-group">
          <%= f.label :vehicle_description %>
          <%= f.text_field :vehicle_description, class: 'form-control', required: true %>
        </fieldset>
      </div>
      <div class="col-md-3">
        <fieldset class="form-group">
          <%= f.label :year %>
          <%= f.number_field :year, class: 'form-control', required: true %>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <fieldset class="form-group">
          <%= f.label :price %>
          <div class="input-group">
            <span class="input-group-addon">
              <span class="fa fa-dollar"></span>
            </span>
            <%= f.text_field :price, class: 'form-control',
              placeholder: 'Ingrese el monto', required: true %>
          </div>
        </fieldset>
      </div>
      <div class="col-md-3">
        <fieldset class="form-group">
          <%= f.label :minimum_advance %>
          <div class="input-group">
            <span class="input-group-addon">
              <span class="fa fa-dollar"></span>
            </span>
            <%= f.text_field :minimum_advance, class: 'form-control',
              placeholder: 'Ingrese el monto', required: true %>
          </div>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <fieldset class="form-group">
          <%= f.label :financed %>
          <div class="input-group">
            <span class="input-group-addon">
              <span class="fa fa-dollar"></span>
            </span>
            <%= f.text_field :financed, class: 'form-control',
              placeholder: 'Ingrese el monto' %>
          </div>
        </fieldset>
      </div>
      <div class="col-md-2">
        <fieldset class="form-group">
          <%= f.label :installments %>
          <%= f.number_field :installments, class: 'form-control' %>
        </fieldset>
      </div>
      <div class="col-md-3">
        <fieldset class="form-group">
          <%= f.label :installments_cost %>
          <div class="input-group">
            <span class="input-group-addon">
              <span class="fa fa-dollar"></span>
            </span>
            <%= f.text_field :installments_cost, class: 'form-control',
              placeholder: 'Ingrese el monto' %>
          </div>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <fieldset class="form-group">
          <%= f.label :expenses %>
          <div class="input-group">
            <span class="input-group-addon">
              <span class="fa fa-dollar"></span>
            </span>
            <%= f.text_field :expenses, class: 'form-control',
              placeholder: 'Ingrese el monto' %>
          </div>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <fieldset class="form-group">
          <%= f.label :notes %>
          <%= f.text_area :notes, class: 'form-control' %>
        </fieldset>
      </div>
    </div>

  </section>
</article>

<div class="row">
  <div class="col-md-12">
    <fieldset class="form-group">
      <%= f.submit 'Guardar', class: 'btn btn-success', data: { 'disable-with' => 'Guardando...' } %>
    </fieldset>
  </div>
</div>

<% end %>

app/views/budgets/edit.html.erb
<header class="content-header">
  <h1>Editar datos de presupuesto
    <%= back_to_link 'Volver', '', 'pull-right' %>
  </h1>
</header>

<section class="content">
  <%= render 'form' %>
</section>

app/views/budgets/index.html.erb
<header class="content-header">
  <%= link_to 'Nuevo Presupuesto', new_budget_path, class: 'btn btn-primary pull-right' %>
  <h1>Presupuestos</h1>
</header>

<section class="content">

  <article class="box box-primary">
    <section class="box-body">

      <%= render 'filter' %>

      <table class="table table-custom table-hover">
        <thead>
          <tr>
            <th>Fecha</th>
            <th>Vehículo</th>
            <th>Año</th>
            <th>Precio</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <%= render @presenter.budgets %>
        </tbody>
      </table>

      <%= paginate @presenter.budgets %>

      <%= content_tag :p, 'No se encontraron presupuestos', class: 'text-center' unless @presenter.budgets.any? %>

    </section>
  </article>

</section>

<% if @budget_to_print %>
  <%= hidden_field_tag :print_url, budget_url(@budget_to_print, format: :pdf), id: 'js-print-budget' %>
<% end %>

app/views/budgets/new.html.erb
<header class="content-header">
  <h1>Crear un nuevo presupuesto
    <%= back_to_link 'Volver', '#', 'pull-right' %>
  </h1>
</header>

<section class="content">
  <%= render 'form' %>
</section>