config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'edit_profile', to: 'users#edit', as: :edit_profile
  patch 'update_profile', to: 'users#update', as: :update_profile

  resources :customers do
    get :search, on: :collection
  end

  resources :vehicles do
    resources :attachments, only: [:create]
    get 'publish', on: :member
    post 'prepare_to_publish', on: :member, as: :prepare_to_publish
  end

  resources :expenses
  resources :expense_categories do
    get :search, on: :collection
  end

  resources :attachments, only: [:destroy]
  resources :brands
  resources :vehicle_models do
    get :search, on: :collection
  end

  resources :versions, only: [:index, :create]
  resources :coincidences, except: [:edit, :new]
  resources :buyers
  resources :budgets
  resources :sales do
    get 'pre_print_advance_certificate', on: :member
    get 'pre_print_sale_certificate', on: :member
  end

  post 'print_pdf', to: 'printer#print_pdf'

  get 'login', to: 'user_sessions#new', as: :login
  post 'logout', to: 'user_sessions#destroy', as: :logout

  root 'vehicles#index'
end

app/models/vehicle.rb
# == Schema Information
#
# Table name: vehicles
#
#  id                         :integer          not null, primary key
#  brand_id                   :integer
#  vehicle_model_id           :integer
#  version_id                 :integer
#  customer_id                :integer
#  kilometers                 :integer
#  color                      :string
#  details                    :text
#  cost_in_cents              :integer
#  price_in_cents             :integer
#  entered_on                 :date
#  sold_on                    :date
#  is_consignment             :boolean          default(FALSE)
#  is_financed                :boolean          default(FALSE)
#  minimum_advance_in_cents   :integer
#  transfer_amount_in_cents   :integer
#  plate                      :string
#  year                       :integer
#  motor_number               :string
#  chassis_number             :string
#  created_at                 :datetime
#  updated_at                 :datetime
#  is_owner                   :boolean          default(FALSE)
#  has_automatic_transmission :boolean          default(FALSE)
#  is_hdi                     :boolean          default(FALSE)
#

class Vehicle < ActiveRecord::Base

  # -- Scopes
  default_scope -> { order(entered_on: :desc, created_at: :desc) }
  scope :not_sold, -> {
    joins('LEFT JOIN sales on sales.vehicle_id = vehicles.id')
      .where('sales.id is NULL OR sales.sold_on IS NULL').distinct
  }

  # -- Associations
  belongs_to :brand
  belongs_to :version
  belongs_to :vehicle_model
  belongs_to :customer
  has_many :attachments, dependent: :destroy
  has_many :budgets, dependent: :destroy
  has_many :coincidences, dependent: :destroy
  has_one :sale, dependent: :destroy

  # -- Validations
  validates :brand, presence: true
  validates :vehicle_model, presence: true
  validates :version, presence: true
  validates :customer, presence: true, if: :not_owner?
  # validates :entered_on, presence: true, if: :is_owner?
  validates :year, presence: true
  validates :kilometers, presence: true
  validates :color, presence: true
  validates :plate, uniqueness: true, allow_blank: true

  # -- Misc
  def not_owner?
    !is_owner?
  end
  
  def sold?
    sold_on.present?
  end

  # Para usar field_in_cents, etc.
  def self.attributes_in_cents
    ['cost', 'price', 'minimum_advance', 'transfer_amount']
  end

  include IntegerInCents

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  before_filter :set_vehicle, only: [:edit, :update, :destroy, :prepare_to_publish, :publish]

  def index
    @presenter = VehiclesPresenter.new(params)
  end

  def show
    @vehicle = Vehicle.find(params[:id]).decorate

    rescue ActiveRecord::RecordNotFound
      flash[:error] = 'El vehículo buscado no existe'
      redirect_to vehicles_path
  end

  def new
    @vehicle = Vehicle.new(vehicle_params)
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      CoincidenceFinder.call(vehicle: @vehicle)

      redirect_to @vehicle,
        notice: 'El vehículo ha sido creado correctamente.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        CoincidenceFinder.call(vehicle: @vehicle)
        format.json { respond_with_bip(@vehicle) }
        format.html {
          redirect_to vehicles_path,
            notice: 'El vehículo ha sido actualizado correctamente.'
        }
      else
        format.json { respond_with_bip(@vehicle) }
        format.html { render :edit }
      end
    end
  end

  def destroy
    if @vehicle.destroy
      redirect_to vehicles_path,
        notice: 'El vehículo ha sido eliminado correctamente.'
    else
      flash[:error] = 'Ocurrió un error al eliminar el vehículo'
      redirect_to vehicles_path
    end
  end

  # Try to gets token from Facebook to publish and redirects to /publish
  def prepare_to_publish
    manager = OauthManager.new(@vehicle)
    @oauth = manager.oauth
    redirect_to manager.url

    rescue Exception => e
      flash[:error] = "No se pudo autenticar con Facebook. #{e}"
      redirect_to vehicles_path
  end

  def publish
    manager = OauthManager.new(@vehicle)
    page_token = manager.get_page_access_token(facebook_params[:code])
    response = FacebookPublisher.new(@vehicle.decorate, page_token).post()

    if response[:status] == :ok
      flash[:success] = 'El vehículo se ha publicado en Facebook exitosamente'
    else
      flash[:error] = 'Ocurrió un error al intentar conectarse con Facebook'
    end

    redirect_to @vehicle
  end


  private

  def facebook_params
    params.permit(:code)
  end

  def vehicle_params
    params.require(:vehicle).permit(:kilometers, :color, :details, :cost,
            :price, :entered_on, :sold_on, :is_exchange, :is_consignment,
            :is_financed, :minimum_advance, :transfer_amount, :plate,
            :year, :motor_number, :chassis_number, :vehicle_model_id,
            :is_hdi, :has_automatic_transmission, :vehicle_type,
            :version_id, :brand_id, :customer_id, :is_owner) if params[:vehicle].present?
  end

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

end

app/views/vehicles/_attachments.html.erb
<p class="text-muted">
  Arrastrá los archivos o hacé click en examinar
</p>

<input id="fileupload" type="file" name="attachment[file]"
    data-url="<%= url_for([vehicle, :attachments]) %>" multiple>
<br />
<div id="js-progress-bar" class="progress md">
  <div class="progress-bar progress-bar-aqua"></div>
</div>

<br />

<div id="js-attachments" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <%= render vehicle.attachments %>
  </div>
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="fa fa-angle-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="fa fa-angle-right"></span>
  </a>
</div>

app/views/vehicles/_extra_data.html.erb
<div class="box box-primary">

  <div class="box-header with-border">
    <h3 class="box-title">
      <span class="fa fa-file-text-o"></span>
      Otros
    </h3>
  </div>

  <div class="box-body">

    <div class="row">
      <div class="col-md-12">
        <fieldset class="form-group">
          <%= f.check_box :is_hdi %>
          <%= f.label :is_hdi %>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <fieldset class="form-group">
          <%= f.check_box :has_automatic_transmission %>
          <%= f.label :has_automatic_transmission %>
        </fieldset>
      </div>
    </div>


  </div>

</div>

app/views/vehicles/_filter.html.erb
<%= form_for @presenter.filter, url: :vehicles, method: :get do |f| %>

  <%= f.hidden_field :is_owner %>

  <div class="row">
    <div class="col-md-2">
      <fieldset class="form-group">
        <%= f.label :plate %>
        <%= f.search_field :plate, class: 'form-control',
              placeholder: 'Ingrese la patente',
                autofocus: true
        %>
      </fieldset>
    </div>

    <div class="col-md-2">
      <fieldset class="form-group">
        <%= f.label :brand %>
        <%= f.search_field :brand, class: 'form-control',
              placeholder: 'Ingrese la marca'
        %>
      </fieldset>
    </div>

    <div class="col-md-2">
      <fieldset class="form-group">
        <%= f.label :vehicle_model %>
        <%= f.search_field :vehicle_model, class: 'form-control',
              placeholder: 'Ingrese el modelo'
        %>
      </fieldset>
    </div>

    <div class="col-md-3">
      <fieldset class="form-group">
        <%= f.label :name %>
        <%= f.search_field :name, class: 'form-control',
              placeholder: 'Ingrese nombre o apellido'
        %>
      </fieldset>
    </div>

    <div class="col-md-3">
      <fieldset class="form-group">
        <div class="fake-label"></div>
          <%= f.submit 'Filtrar', class: 'btn btn-primary',
                'data-disable-with' => 'Filtrando...' %>
          <%= link_to 'Limpiar', [:vehicles], class: 'btn btn-default',
                'data-disable-with' => 'Espere...' %>
      </fieldset>
    </div>

  </div>

<% end %>

app/views/vehicles/_financial_data.html.erb
<div class="box box-primary">

  <div class="box-header with-border">
    <h3 class="box-title">
      <span class="fa fa-money"></span>
      Datos de financiación
    </h3>
  </div>

  <div class="box-body">

    <div class="row">
      <div class="col-md-12">
        <fieldset class="form-group">
          <%= f.check_box :is_financed %> <%= f.label :is_financed, 'Permite financiación' %>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <fieldset class="form-group">
          <%= optional_label f, :minimum_advance %>
          <div class="input-group">
            <span class="input-group-addon">
              <span class="fa fa-dollar"></span>
            </span>
            <%= f.text_field :minimum_advance, class: 'form-control',
                  placeholder: 'Ingrese el monto mínimo' %>
          </div>
        </fieldset>
      </div>
    </div>

  </div>

</div>

app/views/vehicles/_form.html.erb
<%= form_for @vehicle do |f| %>

<div class="row">
  <div class="col-md-12">
    <fieldset class="form-group">
      <%= f.submit 'Guardar vehículo', class: 'btn btn-success', data: { 'disable-with' => 'Guardando...' } %>
    </fieldset>
  </div>
</div>
<article>
  <section>

    <div class="row">

      <div class="col-md-9">
        <%= render partial: 'general_data', locals: {f: f} %>
      </div>

      <div class="col-md-3">
        <div class='row'>
          <div class="col-md-12">
            <%= render partial: 'financial_data', locals: {f: f} %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <%= render partial: 'register_data', locals: {f: f} %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <%= render partial: 'extra_data', locals: {f: f} %>
          </div>
        </div>
      </div>
    </div>
  </section>
</article>

<div class="row">
  <div class="col-md-12">
    <fieldset class="form-group">
      <%= f.submit 'Guardar vehículo', class: 'btn btn-success', data: { 'disable-with' => 'Guardando...' } %>
    </fieldset>
  </div>
</div>

<% end %>

app/views/vehicles/_general_data.html.erb
<div class="box box-primary">

  <div class="box-header with-border">
    <h3 class="box-title">
      <span class="fa fa-car"></span>
      Datos generales
    </h3>
  </div>

  <div class="box-body">

    <% if f.object.is_owner? %>
      <%= f.hidden_field :is_owner, value: f.object.is_owner? %>
    <% else %>
      <div class="row">
        <div class="col-md-10">
          <fieldset class="form-group">
            <%= f.label :customer_id %>
            <%= f.hidden_field :customer_id, class: 'select2', required: true,
              data: { behavior: 'searchCustomer', url: search_customers_path, 'record-id' => @vehicle.customer.try(:customer_id),
                      'record-text' => @vehicle.customer.try(:to_s) } %>
          </fieldset>
        </div>
        <div class="col-md-2">
          <div class="form-group">
            <div class="fake-label"></div>
            <%= link_to 'Nuevo', new_customer_path(modal: true), class: 'btn btn-primary',
              data: { behavior: 'ajax-modal', target: '#js-modal' } %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-4">
        <fieldset class="form-group">
          <%= f.label :brand_id %>
          <%= f.text_field :brand_id, id: 'js-brand',
            data: { data: Brand.all.map { |b| { id: b.id, text: b.name } } },
                  class: 'form-control' %>
        </fieldset>
      </div>

      <div class="col-md-4">
        <fieldset class="form-group">
          <%= f.label :vehicle_model_id %>
          <%= f.text_field :vehicle_model_id, id: 'js-vehicle-model',
                class: 'form-control' %>
        </fieldset>
      </div>

      <div class="col-md-4">
        <fieldset class="form-group">
          <%= f.label :version_id %>
          <%= f.text_field :version_id, id: 'js-version',
                class: 'form-control' %>
        </fieldset>
      </div>
    </div>


    <div class="row">
      <div class="col-md-4">
        <fieldset class="form-group">
          <%= optional_label f, :vehicle_type %>
          <%= f.text_field :vehicle_type, class: 'form-control', placeholder: 'Ingrese el tipo' %>
        </fieldset>
      </div>

      <div class="col-md-4">
        <fieldset class="form-group">
          <%= f.label :color %>
          <%= f.text_field :color, class: 'form-control', placeholder: 'Ingrese un color', required: true %>
        </fieldset>
      </div>

      <div class="col-md-4">
        <fieldset class="form-group">
          <%= f.label :year %>
          <%= f.text_field :year, class: 'form-control', placeholder: 'Ingrese el año' %>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <fieldset class="form-group">
          <%= f.label :kilometers %>
          <%= f.text_field :kilometers, class: 'form-control',
                placeholder: 'Ingrese el kilometraje' %>
        </fieldset>
      </div>

      <div class="col-md-4">
        <fieldset class="form-group">
          <% if f.object.is_owner? %>
            <%= optional_label f, :cost %>
          <% else %>
            <%= optional_label f, "Pretendido por el dueño" %>
          <% end %>
          <div class="input-group">
            <span class="input-group-addon">
              <span class="fa fa-dollar"></span>
            </span>
            <%= f.text_field :cost, class: 'form-control',
              placeholder: 'Ingrese el monto' %>
          </div>
          <p class="help-message">Este valor quedará oculto para los clientes</p>
        </fieldset>
      </div>

      <div class="col-md-4">
        <fieldset class="form-group">
          <%= optional_label f, :price %>
          <div class="input-group">
            <span class="input-group-addon">
              <span class="fa fa-dollar"></span>
            </span>
            <%= f.text_field :price, class: 'form-control',
                placeholder: 'Ingrese el precio de venta' %>
          </div>
          <p class="help-message">Este valor será visible para los clientes</p>
        </fieldset>
      </div>

    </div>

    <div class="row">
      <div class="col-md-4">
        <fieldset class="form-group">
          <%= optional_label f, :transfer_amount %>
          <div class="input-group">
            <span class="input-group-addon">
              <span class="fa fa-dollar"></span>
            </span>
            <%= f.text_field :transfer_amount, class: 'form-control',
                  placeholder: 'Ingrese el costo de la transferencia' %>
          </div>
        </fieldset>
      </div>
      <div class="col-md-4">
        <fieldset class="form-group">
          <% if f.object.is_owner? %>
            <%= f.label :entered_on %>
          <% else %>
            <%= optional_label f, :entered_on %>
          <% end %>
          <div class='input-group date datepicker'>
            <span class="input-group-addon">
              <span class="fa fa-calendar"></span>
            </span>
            <%= f.text_field :entered_on, class: 'form-control' %>
          </div>
        </fieldset>
      </div>

      <div class="col-md-4">
        <fieldset class="form-group">
          <%= optional_label f, :sold_on %>
          <div class='input-group date datepicker'>
            <span class="input-group-addon">
              <span class="fa fa-calendar"></span>
            </span>
            <%= f.text_field :sold_on, class: 'form-control' %>
          </div>
        </fieldset>
      </div>
    </div>


    <div class="row">
      <br />

      <div class="col-md-4">
        <fieldset class="form-group">
          <%= f.check_box :is_consignment %>
          <%= f.label :is_consignment, 'Consignación' %>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <fieldset class="form-group">
          <%= optional_label f, :details %>
          <%= f.text_area :details, class: 'form-control',
                placeholder: 'Ingrese una descripción' %>
        </fieldset>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/_prepare_to_publish.html.erb
<%= form_tag prepare_to_publish_vehicle_path(id: @vehicle.id), remote: true do |f| %>

<article>
  <section>
    <div class="col-md-6">
      <fieldset class="form-group">
        <%= label_tag :message %>
        <%= text_field_tag :message, class: 'form-control', required: true %>
      </fieldset>
    </div>
  </section>
</article>

<div class="row">
  <div class="col-md-12">
    <fieldset class="form-group">
      <%= submit_tag 'Publicar', class: 'btn btn-success', data: { 'disable-with' => 'Guardando...' } %>
    </fieldset>
  </div>
</div>

<% end %>

app/views/vehicles/_register_data.html.erb
<div class="box box-primary">
  
  <div class="box-header with-border">
    <h3 class="box-title">
      <span class="fa fa-file-text-o"></span>
      Datos del registro
    </h3>
  </div>

  <div class="box-body">
    
    <div class="row">
      <div class="col-md-12">
        <fieldset class="form-group">
          <%= optional_label f, :plate %>
          <%= f.text_field :plate, class: 'form-control', placeholder: 'Ingrese una patente' %>
        </fieldset>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-12">
        <fieldset class="form-group">
          <%= optional_label f, :motor_number %>
          <%= f.text_field :motor_number, class: 'form-control', placeholder: 'Ingrese un número de motor' %>
        </fieldset>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-12">
        <fieldset class="form-group">
          <%= optional_label f, :chassis_number %>
          <%= f.text_field :chassis_number, class: 'form-control', placeholder: 'Ingrese un número de chasis' %>
        </fieldset>
      </div>
    </div>

  </div>

</div>

app/views/vehicles/_vehicle.html.erb
<tr id="<%= dom_id(vehicle) %>" class="<%= vehicle.klass %>">

  <td align="left">
    <%= link_to vehicle.identification, vehicle  %>
    <%= vehicle.sale_advance_badge %>
  </td>
  <td align="center"> <%= vehicle.plate %> </td>
  <td align="center"> <%= vehicle.color %> </td>
  <td align="center"> <%= vehicle.year %> </td>
  <td align="center"> <%= vehicle.kilometers %> </td>
  <td align="right">  <%= vehicle.price %> </td>

  <td align="right">
    <%= link_to 'Editar', edit_vehicle_path(vehicle), class: 'btn btn-xs btn-primary' %>
    <%= link_to 'Eliminar', vehicle, method: :delete,
        data: {confirm: '¿Está seguro?'}, class: 'btn btn-xs btn-danger' %>
  </td>

</tr>

app/views/vehicles/edit.html.erb
<header class="content-header">
  <h1>Editar datos del vehículo
    <%= back_to_link 'Volver', '', 'pull-right' %>
  </h1>
</header>

<section class="content">
  <%= render 'form' %>
</section>

app/views/vehicles/index.html.erb
<header class="content-header">
  <%= link_to new_vehicle_path, class: 'btn btn-primary pull-right' do %>
    <%= icon :plus %>
    Vehiculo para la venta
  <% end %>
  <%= link_to new_vehicle_path(vehicle: {is_owner: true}),
        class: 'btn btn-primary pull-right', style: 'margin-right: 10px;' do %>
    <%= icon :plus %>
    Vehiculo propio
  <% end %>
  <h1> <%= @presenter.title %> </h1>
</header>

<section class="content">

  <article class="box box-primary">
    <section class="box-body">

      <%= render 'filter' %>

      <table class="table table-custom table-hover">
        <thead>
          <tr>
            <th class="pull-left">Vehículo</th>
            <th>Patente</th>
            <th>Color</th>
            <th>Año</th>
            <th>Kilómetros</th>
            <th>Precio público</th>

            <th></th>
          </tr>
        </thead>

        <tbody>
          <%= render @presenter.vehicles %>
        </tbody>
      </table>

      <%= paginate @presenter.vehicles %>

      <%= content_tag :p, 'No se encontraron vehículos', class: 'text-center' unless @presenter.vehicles.any? %>

    </section>
  </article>

</section>

app/views/vehicles/new.html.erb
<header class="content-header">
  <h1>Crear un nuevo vehículo
    <%= back_to_link 'Volver', vehicles_path, 'pull-right' %>
  </h1>
</header>

<section class="content">
  <%= render 'form' %>
</section>

app/views/vehicles/show.html.erb
<header class="content-header">
  <h1>
    Detalle del vehículo
    <%= back_to_link 'Volver', '', 'pull-right' %>
  </h1>
</header>

<section class="content">

  <div class="row">

    <div class="col-md-4">
      <%= render partial: 'vehicles/show/profile',
                      locals: { vehicle: @vehicle } %>
      <%= render partial: 'vehicles/show/financial_data',
                      locals: { vehicle: @vehicle } %>
      <%= render partial: 'vehicles/show/register_data',
                      locals: { vehicle: @vehicle } %>
      <%= render partial: 'vehicles/show/extra_data',
                      locals: { vehicle: @vehicle } %>
    </div>

    <div class="col-md-8">
      <%= render partial: "attachments", locals: { vehicle: @vehicle } %>
    </div>

  </div>
</section>