config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'edit_profile', to: 'users#edit', as: :edit_profile
  patch 'update_profile', to: 'users#update', as: :update_profile

  resources :customers do
    get :search, on: :collection
  end

  resources :vehicles do
    resources :attachments, only: [:create]
    get 'publish', on: :member
    post 'prepare_to_publish', on: :member, as: :prepare_to_publish
  end

  resources :expenses
  resources :expense_categories do
    get :search, on: :collection
  end

  resources :attachments, only: [:destroy]
  resources :brands
  resources :vehicle_models do
    get :search, on: :collection
  end

  resources :versions, only: [:index, :create]
  resources :coincidences, except: [:edit, :new]
  resources :buyers
  resources :budgets
  resources :sales do
    get 'pre_print_advance_certificate', on: :member
    get 'pre_print_sale_certificate', on: :member
  end

  post 'print_pdf', to: 'printer#print_pdf'

  get 'login', to: 'user_sessions#new', as: :login
  post 'logout', to: 'user_sessions#destroy', as: :logout

  root 'vehicles#index'
end

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id               :integer          not null, primary key
#  sold_on          :date
#  customer_id      :integer
#  vehicle_id       :integer
#  advance_in_cents :integer          default(0)
#  status           :integer          default(0)
#  price_in_cents   :integer
#  notes            :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Sale < ActiveRecord::Base

  # -- Scopes
  scope :has_finished, -> { where.not('sales.sold_on is null') }

  # -- Associations
  belongs_to :customer
  belongs_to :vehicle

  # -- Validations
  validates :customer, presence: true
  validates :vehicle, presence: true
  validates :price, presence: true
  validates :advance, presence: true
  validates :advance_delivered_on, presence: true

  # -- Misc
  enum status: { pending: 0, finished: 1  }

  # Para usar field_in_cents, etc.
  def self.attributes_in_cents
    ['price', 'expenses', 'advance', 'cash', 'transfer_amount']
  end

  include IntegerInCents

  def sold?
    !sold_on.nil? && !sold_on.blank?
  end


end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  before_filter :set_sale, only: [:show, :edit, :update, :destroy,
                                  :pre_print_advance_certificate, :pre_print_sale_certificate]

  # GET /sales
  def index
    @presenter = SalesPresenter.new(params)
  end

  # GET /sales/:id
  def show
    @presenter = SalePresenter.new(@sale)
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /sales/new
  def new
    @sale = new_sale_from_vehicle
  end

  # POST /sales
  def create
    @sale = Sale.new(sale_params)
    @sale.transfer_amount = @sale.vehicle.transfer_amount

    if @sale.save
      update_vehicle()
      redirect_to @sale, notice: 'La venta ha sido creada con éxito'
    else
      render :new
    end
  end

  # GET /sales/:id/edit
  def edit
  end

  # PUT /sales/:id
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        update_vehicle()
        format.json { respond_with_bip(@sale) }
        format.html {
          redirect_to @sale, notice: 'La venta se ha actualizado correctamente'
        }
      else
        format.json { respond_with_bip(@sale) }
        format.html {
          @vehicle = @sale.vehicle
          render :edit
        }
      end
    end
  end

  # DELETE /sales/:id
  def destroy
    if @sale.destroy
      @sale.vehicle.update(sold_on: nil)
      CoincidenceFinder.call(vehicle: @sale.vehicle) # Actualizo coincidencias

      redirect_to sales_path,
        notice: 'La venta sido eliminada correctamente.'
    else
      flash[:error] = 'Ocurrió un error al eliminar la venta'
      redirect_to sales_path
    end
  end

  # GET /sales/:id/pre_print_advance_certificate
  def pre_print_advance_certificate
    @content = AdvanceCertificate.new(@sale).content
  end

  # GET /sales/:id/pre_print_sale_certificate
  def pre_print_sale_certificate
    @content = SaleCertificate.new(@sale).content
  end


  private

  def set_sale
    @sale = Sale.find(params[:id])
  end

  def sale_params
    params.require(:sale).permit(:vehicle_id, :price, :notes, :sold_on,
                                 :advance, :customer_id, :advance_delivered_on,
                                 :cash, :expenses, :transfer_amount)
  end

  def new_sale_from_vehicle
    @vehicle = Vehicle.find(params[:vehicle_id]).decorate
    Sale.new(
      vehicle_id: @vehicle.id,
      price: @vehicle.unformatted_price
    )
  end

  def update_vehicle
    if sale_params[:sold_on].present?
      @sale.vehicle.update(sold_on: sale_params[:sold_on])
      CoincidenceFinder.call(vehicle: @sale.vehicle) # Actualizo coincidencias
    end
  end

end

app/views/sales/_filter.html.erb
<%= form_for @presenter.filter, url: :sales, method: :get do |f| %>

  <div class="row">
    <div class="col-md-3">
      <fieldset class="form-group">
        <%= f.label :vehicle_model_id, 'Marca y Modelo' %>
        <%= f.hidden_field :vehicle_model_id, class: 'select2 js-vehicle-model',
              data: { behavior: 'searchBrandAndModel', url: search_vehicle_models_path(with_brand: true),
                      record_id: f.object.vehicle_model_id,
                      record_text: f.object.brand_and_model_name } %>
      </fieldset>
    </div>

    <div class="col-md-3">
      <fieldset class="form-group">
        <%= f.label :from %>
        <div class='input-group date datepicker'>
          <span class="input-group-addon">
            <span class="fa fa-calendar"></span>
          </span>
          <%= f.text_field :from, class: 'form-control' %>
        </div>
      </fieldset>
    </div>

    <div class="col-md-3">
      <fieldset class="form-group">
        <%= f.label :to %>
        <div class='input-group date datepicker'>
          <span class="input-group-addon">
            <span class="fa fa-calendar"></span>
          </span>
          <%= f.text_field :to, class: 'form-control' %>
        </div>
      </fieldset>
    </div>


    <div class="col-md-3">
      <div class="fake-label"></div>
      <%= f.submit 'Filtrar', class: 'btn btn-primary',
              'data-disable-with' => 'Filtrando...' %>
      <%= link_to 'Limpiar', [:sales], class: 'btn btn-default',
            'data-disable-with' => 'Espere...' %>
    </div>

  </div>

  <div class="row">
    <div class="col-md-3">
      <fieldset class="form-group">
        <%= f.check_box :hide_not_finished %>
        <%= f.label :hide_not_finished %>
      </fieldset>
    </div>
  </div>

<% end %>

app/views/sales/_form.html.erb
<%= form_for @sale do |f| %>
  <%= f.hidden_field :vehicle_id %>

<article class="box box-primary">

  <section class="box-body">

    <div class="row">
      <div class="col-md-4">
        <fieldset class="form-group">
          <%= label_tag 'Vehículo'  %>
          <%= text_field_tag :vehicle, @sale.vehicle.decorate.identification,
                class: 'form-control disabled', disabled: true  %>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <fieldset class="form-group">
          <%= f.label :customer_id %>
          <%= f.hidden_field :customer_id, class: 'select2', required: true,
            data: { behavior: 'searchCustomer', url: search_customers_path,
                    'record-id' => @sale.customer.try(:customer_id),
                    'record-text' => @sale.customer.try(:to_s) } %>
        </fieldset>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <div class="fake-label"></div>
          <%= link_to 'Nuevo', new_customer_path(modal: true), class: 'btn btn-primary',
            data: { behavior: 'ajax-modal', target: '#js-modal' } %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <fieldset class="form-group">
          <%= f.label :price %>
          <div class="input-group">
            <span class="input-group-addon">
              <span class="fa fa-dollar"></span>
            </span>
            <%= f.text_field :price, class: 'form-control',
              placeholder: 'Ingrese el monto', required: true %>
          </div>
        </fieldset>
      </div>
      <div class="col-md-3">
        <fieldset class="form-group">
          <%= f.label :cash %>
          <div class="input-group">
            <span class="input-group-addon">
              <span class="fa fa-dollar"></span>
            </span>
            <%= f.text_field :cash, class: 'form-control',
              placeholder: 'Ingrese el monto', required: true %>
          </div>
        </fieldset>
      </div>
    </div>

    <div class="row">

      <div class="col-md-3">
        <fieldset class="form-group">
          <%= f.label :advance %>
          <div class="input-group">
            <span class="input-group-addon">
              <span class="fa fa-dollar"></span>
            </span>
            <%= f.text_field :advance, class: 'form-control',
              placeholder: 'Ingrese el monto', required: true %>
          </div>
        </fieldset>
      </div>
      <div class="col-md-3">
        <fieldset class="form-group">
          <%= f.label :advance_delivered_on %>
          <div class='input-group date datepicker'>
            <span class="input-group-addon">
              <span class="fa fa-calendar"></span>
            </span>
            <%= f.text_field :advance_delivered_on, class: 'form-control', required: true %>
          </div>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <fieldset class="form-group">
          <%= f.label :sold_on %>
          <div class='input-group date datepicker col-md-4'>
            <span class="input-group-addon">
              <span class="fa fa-calendar"></span>
            </span>
            <%= f.text_field :sold_on, class: 'form-control' %>
          </div>
          <p class="help-block">Dejar vacío si no se concretó la totalidad de la venta</p>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <fieldset class="form-group">
          <%= f.label :notes %>
          <%= f.text_area :notes, class: 'form-control', rows: 8 %>
        </fieldset>
      </div>
    </div>

  </section>
</article>

<div class="row">
  <div class="col-md-12">
    <fieldset class="form-group">
      <%= f.submit 'Guardar', class: 'btn btn-success', data: { 'disable-with' => 'Guardando...' } %>
    </fieldset>
  </div>
</div>

<% end %>

app/views/sales/_sale.html.erb
<tr id="<%= dom_id(sale) %>" data-sale-id="<%= sale.id %>" class="<%= sale.klass %>">

  <td>
    <%= link_to sale.vehicle.decorate.identification, sale %>
   </td>
  <td> <%= sale.sold_on %> </td>
  <td class="text-center">
    <%= sale.vehicle_cost %>
  </td>
  <td class="text-center"> <%= sale.price %> </td>
  <td class="text-center"> <%= sale.cash %> </td>
  <td class="text-center"> <%= sale.expenses %> </td>
  <td class="text-right"> <%= sale.difference %> </td>
  <td>
    <%= link_to fa_icon(:pencil), edit_sale_path(sale), title: 'Editar los datos de la Venta', class: 'btn btn-xs btn-primary' %>
    <%= link_to fa_icon(:trash), sale, method: :delete,
        data: {confirm: '¿Está seguro?'}, title: 'Eliminar Venta', class: 'btn btn-xs btn-danger' %>
    <%= sale.customer_btn %>
  </td>

</tr>

app/views/sales/_totals.html.erb
<tfoot id="js-sales-totals-row">
  <tr style="background: #f0f0f0;">
    <td> <b> <%= presenter.sales.count %> vehículos </b> </td>
    <td></td>
    <td class="text-center"><b><%= presenter.total_cost %></b></td>
    <td class="text-center"><b><%= presenter.total_price %></b></td>
    <td class="text-center"><b><%= presenter.total_cash %></b></td>
    <td></td>
    <td class="text-right"><b><%= presenter.total_difference %></b></td>
    <td></td>
  </tr>
  <tr>
    <td colspan="5"> </td>
    <td class="text-right"> <b> Gastos </b> </td>
    <td class="text-right"><b><%= number_to_currency presenter.total_expenses %></b></td>
    <td></td>
  </tr>
  <tr>
    <td colspan="5"> </td>
    <td class="text-right"> <b> Ganancia Total </b> </td>
    <td class="text-right"><b><%= number_to_currency presenter.total_profit %></b></td>
    <td></td>
  </tr>
</tfoot>

app/views/sales/edit.html.erb
<header class="content-header">
  <h1>Editar datos de la venta
    <%= back_to_link 'Volver', '', 'pull-right' %>
  </h1>
</header>

<section class="content">
  <%= render 'form' %>
</section>

app/views/sales/index.html.erb
<header class="content-header">
  <h1>Ventas</h1>
</header>

<section class="content">

  <article class="box box-primary">
    <section class="box-body">

      <%= render 'filter' %>

      <table class="table table-custom table-hover">
        <thead>
          <tr>
            <th class="pull-left">Vehículo</th>
            <th>Fecha Venta</th>
            <th>Costo real</th>
            <th>Precio de venta</th>
            <th>En Efectivo</th>
            <th>Gastos</th>
            <th>Ganancia</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <%= render @presenter.sales %>
        </tbody>

        <%= render partial: 'totals', locals: { presenter: @presenter } %>

      </table>

      <%= paginate @presenter.sales %>

      <%= content_tag :p, 'No se encontraron ventas', class: 'text-center' unless @presenter.sales.any? %>

    </section>
  </article>

</section>

app/views/sales/new.html.erb
<header class="content-header">
  <h1>Crear un nueva venta
    <%= back_to_link 'Volver', @vehicle, 'pull-right' %>
  </h1>
</header>

<section class="content">
  <%= render 'form' %>
</section>

app/views/sales/pre_print_advance_certificate.html.erb
<header class="content-header">
  <h1> Crear boleto para seña
    <%= back_to_link 'Volver', @sale, 'pull-right' %>
  </h1>
</header>

<section class="content">
  <%= form_tag print_pdf_path, method: :post, target: '_blank' do %>

    <div class="form-group">
      <%= content_tag 'trix-editor', '', input: 'js-body', class: 'trix-content' %>
      <%= hidden_field_tag :body, @content, id: 'js-body' %>
    </div>

    <%= submit_tag 'Imprimir', class: 'btn btn-success' %>

  <% end %>
</section>

app/views/sales/pre_print_sale_certificate.html.erb
<header class="content-header">
  <h1> Crear boleto compra venta
    <%= back_to_link 'Volver', @sale, 'pull-right' %>
  </h1>
</header>

<section class="content">
  <%= form_tag print_pdf_path, method: :post, target: '_blank' do %>

    <div class="form-group">
      <%= content_tag 'trix-editor', '', input: 'js-body', class: 'trix-content' %>
      <%= hidden_field_tag :body, @content, id: 'js-body' %>
    </div>

    <%= submit_tag 'Imprimir', class: 'btn btn-success' %>

  <% end %>
</section>

app/views/sales/show.html.erb
<header class="content-header">
  <h1>
    Detalle de la venta
    <%= back_to_link 'Volver', @presenter.sale, 'pull-right' %>
  </h1>
</header>

<section class="content">

  <div class="row">

    <div class="col-md-8">
      <div class="box box-primary">
        <div class="box-body box-profile">
          <h3 class="text-center"><%= @presenter.sale.brand_and_model %></h3>
          <h4 class="text-center"><%= @presenter.sale.version %></h4>
          <h4 class="text-center"><b><%= @presenter.sale.specs %></b></h4>
          <p class="text-muted text-center">
            <%= @presenter.sale.sale_situation %>
          </p>

          <br />

          <ul class="list-group list-group-unbordered">
            <li class="list-group-item">
              <b>Comprador</b>
              <span class="text-muted pull-right">
                <%= link_to @presenter.sale.customer, edit_customer_path(@sale.customer) %></span>
            </li>
            <li class="list-group-item">
              <b>Teléfono Comprador</b>
              <span class="text-muted pull-right">
                <span class="text-muted"><%= @presenter.sale.customer.phones %> </span>
            </li>

            <li class="list-group-item">
              <b>Vehículo</b>
              <span class="text-muted pull-right">
                <%= link_to @presenter.sale.vehicle.decorate.identification, @sale.vehicle %></span>
            </li>
            <li class="list-group-item">
              <b>Precio</b>
              <span class="text-muted pull-right"><%= @presenter.sale.price %></span>
            </li>
            <li class="list-group-item">
              <b>Seña</b>
              <span class="text-muted pull-right"><%= @presenter.sale.advance %></span>
            </li>
            <li class="list-group-item">
              <b>Fecha Seña</b>
              <span class="text-muted pull-right"><%= @presenter.sale.advance_delivered_on %></span>
            </li>
            <li class="list-group-item">
              <b>Fecha Venta</b>
              <span class="text-muted pull-right">
                <%= @presenter.sold_on %></span>
            </li>
          </ul>
          <b> Notas </b>
          <div> <%= @presenter.sale.notes %> </div>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">Operaciones</h3>
        </div>
        <div class="box-body">
          <%= link_to '<b>Editar / Finalizar Venta</b>'.html_safe, edit_sale_path(@presenter.sale),
                class: 'btn btn-primary btn-block' %>
          <%= link_to '<b>Imprimir Boleto Seña </b>'.html_safe, [:pre_print_advance_certificate, @presenter.sale],
                class: 'btn btn-warning btn-block' %>
          <%= link_to '<b>Imprimir Boleto Compra Venta </b>'.html_safe, [:pre_print_sale_certificate, @presenter.sale],
                disabled: !@presenter.sale.sold?,
                class: 'btn btn-success btn-block' %>
              <hr>
          <%= @presenter.sale.delete_btn %>
        </div>
      </div>
    </div>

  </div>

</section>

app/views/sales/show.js.erb
$('#<%= dom_id(@presenter.sale) %>').replaceWith('<%= j render @presenter.sale %>');

$('#js-sales-totals-row').replaceWith('<%= j render partial: 'totals', locals: { presenter: SalesPresenter.new({}) } %>');

new App.SalesList(); 
App.initTooltips($('#<%= dom_id(@presenter.sale) %>'));